######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 30 23:07:28 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += netmonitor.h
SOURCES += netmonitor.cpp
