######################################################################
# Automatically generated by qmake (1.07a) Wed Jul 30 23:10:08 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += horizon.h
SOURCES += horizon.cpp
